# Generated by Django 5.2.8 on 2025-11-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='введение название книги')),
                ('image', models.ImageField(upload_to='books/', verbose_name='загрузите фото')),
                ('description', models.TextField(verbose_name='укажиете описание')),
                ('author', models.CharField(default='Ivenov Ivan', max_length=100, verbose_name='укажиет автора')),
                ('genre', models.CharField(choices=[('роман', 'роман'), ('драма', 'драма'), ('лирика', 'лирика'), ('эпос', 'эпос')], max_length=100, verbose_name='роман')),
                ('country', models.CharField(default='США', max_length=100, verbose_name='укажите страну')),
                ('duration', models.PositiveIntegerField(default='100000', verbose_name='количество страниц')),
                ('video', models.URLField(verbose_name='ссылка на обзор')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'book',
                'verbose_name_plural': 'book',
            },
        ),
    ]
