# Generated by Django 5.2.7 on 2025-11-08 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='director',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='trailer',
            new_name='video',
        ),
    ]
